apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rbuysse/gigi.git
    targetRevision: HEAD
    path: a/guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook1
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
