apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rbuysse/gigi.git
    targetRevision: HEAD
    path: b/guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook2
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
